import type { RequirementCriterion } from "@legion/protocol";

/**
 * Acceptance criteria for machine-generated requirements.
 *
 * Protocol 0.2.0 requires every acceptance criterion to say how it is proven.
 * The requirements Legion generates for itself — a phase's planning-source
 * placeholder, bullets scraped out of roadmap prose, an ad-hoc request — carry
 * no such proof, because their source never had one.
 *
 * They are therefore emitted as `manual` criteria with an explicit reason. That
 * is deliberate: an unproven criterion should be visible and countable, not
 * disguised behind a command that would pass regardless of whether the
 * criterion holds. `legion validate` can then report how much of a project's
 * acceptance surface is still unproven.
 */
export const GENERATED_CRITERION_REASON =
  "Generated by Legion from a roadmap or ad-hoc source that defined no acceptance proof. Replace with an executable criterion before treating this as verified.";

const MAX_CRITERION_SLUG_LENGTH = 48;

/**
 * Build a criterion ID from a statement, falling back to the ordinal when the
 * statement has no usable slug characters. IDs must be unique within a
 * requirement, so the index is always appended.
 */
export function criterionIdFor(statement: string, index: number): string {
  const slug = statement
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, MAX_CRITERION_SLUG_LENGTH)
    .replace(/-+$/g, "");
  return slug.length > 0 ? `ac_${slug}-${index + 1}` : `ac_criterion-${index + 1}`;
}

export function generatedCriterion(statement: string, index: number): RequirementCriterion {
  return {
    id: criterionIdFor(statement, index),
    statement,
    proof: {
      mode: "manual",
      reason: GENERATED_CRITERION_REASON
    }
  };
}

export function generatedCriteria(statements: readonly string[]): readonly RequirementCriterion[] {
  return statements.map((statement, index) => generatedCriterion(statement, index));
}
