#!/usr/bin/env node
import { spawn } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const SCRIPT_PATH = fileURLToPath(import.meta.url);
const ROOT = resolve(dirname(SCRIPT_PATH), "..");

const VALIDATE_NEXT_PLAN = [
  { id: "typecheck", command: "pnpm run typecheck" },
  { id: "package-boundaries", command: "pnpm run check:boundaries" },
  { id: "worker-bundles", command: "pnpm run check:worker-bundles" },
  {
    id: "default-runtime-scan",
    command: "node scripts/scan-default-runtime.mjs"
  },
  {
    id: "runtime-import-boundaries",
    command: "node scripts/scan-runtime-import-boundaries.mjs"
  },
  { id: "schema-generation", command: "pnpm --filter @legion/protocol generate:schemas" },
  { id: "artifact-schema-generation", command: "pnpm --filter @legion/artifacts generate:schemas" },
  { id: "protocol-docs", command: "node scripts/validate-next.mjs --generate-protocol-docs" },
  { id: "schema-doc-drift", command: "node scripts/validate-next.mjs --check-generated-drift" },
  { id: "package-contents", command: "pnpm run check:package-contents" },
  { id: "tests", command: "pnpm run test" },
  { id: "npm-pack", command: "npm pack --dry-run --json" },
  { id: "pnpm-pack", command: "pnpm pack --dry-run" }
];

const SCHEMA_FILE_NAMES = {
  taskContract: "task-contract",
  taskRun: "task-run",
  evidenceBundle: "evidence",
  reviewDecision: "review",
  fixtureCorpus: "fixture-corpus",
  compatibilityFixture: "compatibility-fixture",
  commandEnvelope: "command-envelope",
  commandResult: "command-result",
  queryRequest: "query-request",
  queryResponse: "query-response"
};

export function getValidateNextPlan() {
  return VALIDATE_NEXT_PLAN.map((step) => ({ ...step }));
}

async function importBuiltModule(root, relativePath) {
  try {
    return await import(pathToFileURL(join(root, relativePath)).href);
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ERR_MODULE_NOT_FOUND") {
      throw new Error(`Protocol documentation requires built package output. Run "pnpm run typecheck" before generating docs. Missing: ${relativePath}`);
    }

    throw error;
  }
}

function withTrailingNewline(contents) {
  return contents.endsWith("\n") ? contents : `${contents}\n`;
}

function generatedNotice(sources) {
  const sourceList = sources.map((source) => `- ${source}`).join("\n");
  return [
    "<!-- Generated by scripts/validate-next.mjs --generate-protocol-docs. Do not edit by hand. -->",
    "",
    "Source inputs:",
    sourceList
  ].join("\n");
}

function escapeCell(value) {
  return String(value).replace(/\|/g, "\\|");
}

function markdownTable(headers, rows) {
  return [
    `| ${headers.map(escapeCell).join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.map(escapeCell).join(" | ")} |`)
  ].join("\n");
}

function schemaPath(group, name) {
  return `schemas/${group}/${SCHEMA_FILE_NAMES[name] ?? name}.schema.json`;
}

function schemaRows(group, schemas) {
  return Object.entries(schemas).map(([name, schema]) => [
    group,
    `\`${name}\``,
    schema.title,
    `\`${schema.$id}\``,
    `\`${schemaPath(group, name)}\``
  ]);
}

function renderSchemasDoc(protocol) {
  const rows = [
    ...schemaRows("primitives", protocol.primitiveJsonSchemas),
    ...schemaRows("entities", protocol.entityJsonSchemas),
    ...schemaRows("events", protocol.eventJsonSchemas),
    ...schemaRows("api", protocol.apiJsonSchemas)
  ];

  return withTrailingNewline([
    generatedNotice([
      "packages/protocol/src/primitives/schema-documents.ts",
      "packages/protocol/src/entities/schema-documents.ts",
      "packages/protocol/src/events/schema-documents.ts",
      "packages/protocol/src/api/schema-documents.ts",
      "schemas/**"
    ]),
    "",
    "# Legion Protocol Schema Catalog",
    "",
    `Protocol version: \`${protocol.LEGION_PROTOCOL_VERSION}\``,
    "",
    markdownTable(["Group", "Schema", "Title", "Canonical ID", "Committed artifact"], rows)
  ].join("\n"));
}

function renderReadme(protocol, core) {
  const schemaCount =
    Object.keys(protocol.primitiveJsonSchemas).length +
    Object.keys(protocol.entityJsonSchemas).length +
    Object.keys(protocol.eventJsonSchemas).length +
    Object.keys(protocol.apiJsonSchemas).length;
  const eventCount = protocol.EVENT_CATALOG.length;
  const commandCount = protocol.API_COMMAND_TYPES.length;
  const stateMachineCount = Object.keys(core.STATE_MACHINE_TRANSITION_MATRICES).length;

  return withTrailingNewline([
    generatedNotice([
      "packages/protocol/src/**",
      "packages/core/src/state-machines/index.ts",
      "schemas/**"
    ]),
    "",
    "# Legion Next Protocol Documentation",
    "",
    `Protocol version: \`${protocol.LEGION_PROTOCOL_VERSION}\``,
    "",
    "This directory is generated from the typed protocol and core transition sources. Run `pnpm docs:protocol` to refresh it, or `pnpm validate:next` to refresh and fail on drift.",
    "",
    markdownTable(
      ["Surface", "Generated coverage"],
      [
        ["Schema catalog", `${schemaCount} JSON Schema documents across primitives, entities, events, and API contracts.`],
        ["Event contracts", `${eventCount} append-only event types from the event catalog.`],
        ["API contracts", `${commandCount} command types plus query envelope contracts.`],
        ["State machines", `${stateMachineCount} core transition matrices derived from reducer source.`]
      ]
    ),
    "",
    "## Files",
    "",
    "- `schemas.md` catalogs committed JSON Schema artifacts.",
    "- `events.md` documents append-only event contracts.",
    "- `api.md` documents provider-neutral command and query contracts.",
    "- `state-machines.md` documents lifecycle transition matrices."
  ].join("\n"));
}

function renderApiDoc(protocol) {
  return withTrailingNewline([
    generatedNotice(["packages/protocol/src/api/contracts.ts"]),
    "",
    protocol.apiContractDocumentation
  ].join("\n"));
}

function renderEventsDoc(protocol) {
  return withTrailingNewline([
    generatedNotice(["packages/protocol/src/events/envelope.ts"]),
    "",
    protocol.eventContractDocumentation
  ].join("\n"));
}

function renderStateMachineDoc(core) {
  const matrices = Object.values(core.STATE_MACHINE_TRANSITION_MATRICES);
  const summaryRows = matrices.map((matrix) => [
    `\`${matrix.aggregate}\``,
    String(matrix.states.length),
    matrix.terminalStates.map((state) => `\`${state}\``).join(", "),
    String(matrix.transitions.length)
  ]);
  const sections = matrices.flatMap((matrix) => [
    `## ${matrix.aggregate}`,
    "",
    markdownTable(
      ["From", "Event", "To"],
      matrix.transitions.map((transition) => [
        `\`${transition.from}\``,
        `\`${transition.eventType}\``,
        `\`${transition.to}\``
      ])
    )
  ]);

  return withTrailingNewline([
    generatedNotice(["packages/core/src/state-machines/index.ts"]),
    "",
    "# Legion Core State Machines",
    "",
    "The transition matrices below are generated from `STATE_MACHINE_TRANSITION_MATRICES`.",
    "",
    markdownTable(["Aggregate", "States", "Terminal states", "Transitions"], summaryRows),
    "",
    ...sections
  ].join("\n"));
}

export async function renderProtocolDocs(options = {}) {
  const root = options.root ?? ROOT;
  const [protocol, core] = await Promise.all([
    importBuiltModule(root, "packages/protocol/dist/index.js"),
    importBuiltModule(root, "packages/core/dist/index.js")
  ]);

  return {
    "docs/next/protocol/README.md": renderReadme(protocol, core),
    "docs/next/protocol/schemas.md": renderSchemasDoc(protocol),
    "docs/next/protocol/events.md": renderEventsDoc(protocol),
    "docs/next/protocol/api.md": renderApiDoc(protocol),
    "docs/next/protocol/state-machines.md": renderStateMachineDoc(core)
  };
}

export async function writeProtocolDocs(options = {}) {
  const root = options.root ?? ROOT;
  const docs = await renderProtocolDocs({ root });

  await Promise.all(
    Object.entries(docs).map(async ([relativePath, contents]) => {
      const outputPath = join(root, relativePath);
      await mkdir(dirname(outputPath), { recursive: true });
      await writeFile(outputPath, contents, "utf8");
    })
  );

  return docs;
}

function runShellCommand(command, options = {}) {
  const root = options.root ?? ROOT;

  return new Promise((resolveCommand, rejectCommand) => {
    const child = spawn(command, {
      cwd: root,
      env: process.env,
      shell: true,
      stdio: "inherit"
    });

    child.on("error", rejectCommand);
    child.on("exit", (code, signal) => {
      if (code === 0) {
        resolveCommand();
        return;
      }

      rejectCommand(new Error(`Command failed (${signal ?? code}): ${command}`));
    });
  });
}

function captureShellCommand(command, options = {}) {
  const root = options.root ?? ROOT;

  return new Promise((resolveCommand, rejectCommand) => {
    const child = spawn(command, {
      cwd: root,
      env: process.env,
      shell: true,
      stdio: ["ignore", "pipe", "pipe"]
    });
    const stdout = [];
    const stderr = [];

    child.stdout.on("data", (chunk) => stdout.push(chunk));
    child.stderr.on("data", (chunk) => stderr.push(chunk));
    child.on("error", rejectCommand);
    child.on("close", (code, signal) => {
      const output = Buffer.concat(stdout).toString("utf8");
      const errorOutput = Buffer.concat(stderr).toString("utf8");

      if (code === 0) {
        resolveCommand({ stdout: output, stderr: errorOutput });
        return;
      }

      rejectCommand(new Error(`Command failed (${signal ?? code}): ${command}\n${output}${errorOutput}`));
    });
  });
}

export async function checkGeneratedDrift(options = {}) {
  const root = options.root ?? ROOT;

  await runShellCommand("git diff --exit-code -- schemas docs/next/protocol", { root });

  const untracked = await captureShellCommand("git ls-files --others --exclude-standard -- schemas docs/next/protocol", { root });
  if (untracked.stdout.trim().length > 0) {
    throw new Error(`Generated protocol artifacts are untracked:\n${untracked.stdout}`);
  }
}

export async function runValidateNext(options = {}) {
  const root = options.root ?? ROOT;

  for (const step of VALIDATE_NEXT_PLAN) {
    process.stdout.write(`\n[validate:next] ${step.id}: ${step.command}\n`);
    await runShellCommand(step.command, { root });
  }
}

async function main() {
  const args = process.argv.slice(2);

  if (args.includes("--generate-protocol-docs")) {
    await writeProtocolDocs({ root: ROOT });
    return;
  }

  if (args.includes("--check-generated-drift")) {
    await checkGeneratedDrift({ root: ROOT });
    return;
  }

  if (args.includes("--plan")) {
    process.stdout.write(`${JSON.stringify(getValidateNextPlan(), null, 2)}\n`);
    return;
  }

  await runValidateNext({ root: ROOT });
}

if (resolve(process.argv[1] ?? "") === SCRIPT_PATH) {
  main().catch((error) => {
    process.stderr.write(`${error instanceof Error ? error.stack : String(error)}\n`);
    process.exitCode = 1;
  });
}
